apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rucio-pgb-db-target
  namespace: rucio-dune-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: rucio-pgb-db-target
  data:
  - secretKey: DB_HOST
    remoteRef:
      key: okd/okdprod1/rucio-dune-dev/pgbouncer
      property: DB_HOST
  - secretKey: DB_PORT
    remoteRef:
      key: okd/okdprod1/rucio-dune-dev/pgbouncer
      property: DB_PORT
  - secretKey: DB_NAME
    remoteRef:
      key: okd/okdprod1/rucio-dune-dev/pgbouncer
      property: DB_NAME
  - secretKey: DB_USER
    remoteRef:
      key: okd/okdprod1/rucio-dune-dev/pgbouncer
      property: DB_USER
  - secretKey: DB_PASSWORD
    remoteRef:
      key: okd/okdprod1/rucio-dune-dev/pgbouncer
      property: DB_PASSWORD
