apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fnal-db-connstr
  namespace: rucio-dune-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: fnal-db-connstr
  data:
  - secretKey: db-connstr.txt
    remoteRef:
      key: okd/okdprod1/rucio-dune-dev/rucio
      property: db-connstr
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fnal-server-hostcert
  namespace: rucio-dune-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: fnal-server-hostcert
  data:
  - secretKey: hostcert.pem
    remoteRef:
      key: okd/okdprod1/rucio-dune-dev/rucio
      property: server-hostcert
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fnal-server-hostkey
  namespace: rucio-dune-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: fnal-server-hostkey
  data:
  - secretKey: hostkey.pem
    remoteRef:
      key: okd/okdprod1/rucio-dune-dev/rucio
      property: server-hostkey
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fnal-hermes-cert
  namespace: rucio-dune-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: fnal-hermes-cert
  data:
  - secretKey: hostcert.pem
    remoteRef:
      key: okd/okdprod1/rucio-dune-dev/rucio
      property: server-hostcert
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fnal-hermes-key
  namespace: rucio-dune-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: fnal-hermes-key
  data:
  - secretKey: hostkey.pem
    remoteRef:
      key: okd/okdprod1/rucio-dune-dev/rucio
      property: server-hostkey
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fnal-fts-cert
  namespace: rucio-dune-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: fnal-fts-cert
  data:
  - secretKey: usercert.pem
    remoteRef:
      key: okd/okdprod1/rucio-dune-dev/rucio
      property: server-hostcert
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fnal-fts-key
  namespace: rucio-dune-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: fnal-fts-key
  data:
  - secretKey: new_userkey.pem
    remoteRef:
      key: okd/okdprod1/rucio-dune-dev/rucio
      property: server-hostkey
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: server-hostcert
  namespace: rucio-dune-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: ssl-secrets
  data:
  - secretKey: hostcert.pem
    remoteRef:
      key: okd/okdprod1/rucio-dune-dev/rucio
      property: server-hostcert
  - secretKey: hostkey.pem
    remoteRef:
      key: okd/okdprod1/rucio-dune-dev/rucio
      property: server-hostkey
  - secretKey: ca.pem
    remoteRef:
      key: okd/okdprod1/rucio-dune-dev/rucio
      property: server-cafile
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fnal-hostcert
  namespace: rucio-dune-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: fnal-hostcert
  data:
  - secretKey: hostcert.pem
    remoteRef:
      key: okd/okdprod1/rucio-dune-dev/rucio
      property: server-hostcert
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fnal-hostkey
  namespace: rucio-dune-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: fnal-hostkey
  data:
  - secretKey: hostkey.pem
    remoteRef:
      key: okd/okdprod1/rucio-dune-dev/rucio
      property: server-hostkey
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fnal-cafile
  namespace: rucio-dune-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: fnal-cafile
  data:
  - secretKey: ca.pem
    remoteRef:
      key: okd/okdprod1/rucio-dune-dev/rucio
      property: server-cafile
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fnal-idpsecrets
  namespace: rucio-dune-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: fnal-idpsecrets
  data:
  - secretKey: ca.pem
    remoteRef:
      key: okd/okdprod1/rucio-dune-dev/rucio
      property: idpsecrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fnal-globus-client
  namespace: rucio-dune-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: fnal-globus-client
  data:
  - secretKey: globus-client
    remoteRef:
      key: okd/okdprod1/rucio-dune-dev/rucio
      property: globus-client
