apiVersion: apps/v1
kind: Deployment
metadata:
  name: fnal-rucio-server
spec:
  template:
    spec:
      initContainers:
        - name: install-policy-packages
          resources:
            requests:
              cpu: 500m
              memory: 600Mi
            limits:
              cpu: 500m
              memory: 600Mi
      containers:
        - name: httpd-error-log
          image: imageregistry.fnal.gov/docker.io/busybox
          resources:
            requests:
              cpu: 500m
              memory: 600Mi
            limits:
              cpu: 500m
              memory: 600Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fnal-rucio-webui
spec:
  template:
    spec:
      containers:
        - name: httpd-error-log
          image: imageregistry.fnal.gov/docker.io/busybox
          resources:
            requests:
              cpu: 500m
              memory: 600Mi
            limits:
              cpu: 500m
              memory: 600Mi
        - name: webui-log
          image: imageregistry.fnal.gov/docker.io/busybox
          resources:
            requests:
              cpu: 500m
              memory: 600Mi
            limits:
              cpu: 500m
              memory: 600Mi
