---
# Source: rucio-prometheus/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rucio-int-prometheus
  labels:
    app: rucio-prometheus
    chart: rucio-prometheus-1
    release: rucio-int-prometheus
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rucio-prometheus
      release: rucio-int-prometheus
  minReadySeconds: 
  template:
    metadata:
      labels:
        app: rucio-prometheus
        release: rucio-int-prometheus
    spec:
      serviceAccountName: useroot
      volumes:
        - name: prometheus-yml
          configMap:
            name: prometheus-yml
      containers:
        - name: rucio-prometheus
          # image: "imageregistry.fnal.gov/rucio-ams/rucio-ams-prometheus:32"
          image: "imageregistry.fnal.gov/docker.io/prom/prometheus:latest"
          imagePullPolicy: Always
          volumeMounts:
            - name: prometheus-yml
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--web.console.libraries=/usr/share/prometheus/console_libraries"
            - "--web.console.templates=/usr/share/prometheus/consoles"
            - "--log.level=debug"
          # env:
          #   - name: EXPERIMENT
          #     value: "int"
          #   - name: LANDSCAPE_REMOTE_WRITE_ENDPOINT
          #     value: "http://lsdataitb.fnal.gov:9009/api/v1/push"
          resources:
            requests:
              cpu: 600m
              memory: 600Mi
            limits:
              cpu: 600m
              memory: 600Mi
