apiVersion: v1
kind: Service
metadata:
  name: fnal-rucio-server-headless
  namespace: rucio-dune-int
spec:
  clusterIP: None
  selector:
    app: rucio-server
    release: fnal
  ports:
    - name: https
      port: 443
      targetPort: 443
