---
# Source: rucio-messenger/templates/messenger_service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fnal-rucio-messenger-nossl
  labels:
    app: rucio-messenger
    release: fnal
spec:
  type: ClusterIP
  ports:
    - port: 61613
      targetPort: 61613
      protocol: TCP
      name: http
  selector:
    app: rucio-messenger
    release: fnal
---
# Source: rucio-messenger/templates/messenger_service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fnal-rucio-messenger
  labels:
    app: rucio-messenger
    release: fnal
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
    - port: 15671
      targetPort: 15671
      protocol: TCP
      name: management
  selector:
    app: rucio-messenger
    release: fnal
---
# Source: rucio-messenger/templates/messenger_deployment.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fnal-rucio-messenger
  labels:
    app: rucio-messenger
    release: fnal
spec:
  serviceName: fnal-rucio-messenger
  replicas: 1
  selector:
    matchLabels:
      app: rucio-messenger
      release: fnal
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: rucio-messenger
        release: fnal
    spec:
      serviceAccountName: useroot
      volumes:
        - name: ssl-credentials
          secret:
            secretName: ssl-secrets
        - name: rabbitmq-conf
          secret:
            secretName: fnal-rabbitmq-conf
            items:
              - key: enabled_plugins
                path: enabled_plugins
              - key: rabbitmq.conf
                path: rabbitmq.conf
              - key: definitions.json
                path: definitions.json
            defaultMode: 0644
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: rabbitmq-data
      containers:
        - name: rucio-messenger
          image: "imageregistry.fnal.gov/docker.io/rabbitmq:3"
          imagePullPolicy: Always
          command: ["rabbitmq-server"]
          resources:
            requests:
              cpu: 1
              memory: 1Gi
            limits:
              cpu: 1
              memory: 4Gi
          ports:
            - containerPort: 443
            - containerPort: 61613
            - containerPort: 15671
          volumeMounts:
            - name: ssl-credentials
              mountPath: /etc/grid-security/rabbitmq
              readOnly: true
            - name: rabbitmq-conf
              mountPath: /etc/rabbitmq
          env:
            - name: EXPERIMENT
              value: "dune-int"
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq-data
      namespace: rucio-dune-int
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: "3Gi"
