# kustomize.yaml for rucio-dune-dev
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helm-rucio-server.yaml
- helm-rucio-daemons.yaml
- helm-rucio-webui.yaml
- cache.yaml
- prometheus.yaml
- messenger-ss.yaml
- routes.yaml
- grid-certificates-pvc.yaml
- grid-certificates-cronjob.yaml
- grid-certificates-job.yaml

patches:
- path: grid-certificates-patch.yaml
- path: patch-server.yaml
- path: patch-busybox.yaml
- path: patch-renew-fts-proxy-job.yaml
- target:
    kind: Deployment
    labelSelector: "app-group=rucio-daemons"
  path: patch-install-policy-package.yaml

configMapGenerator:
- files:
  - rucio.conf.j2=etc/rucio-server.conf.j2
  name: server-rucio-conf-j2
- files:
  - prometheus.yml=etc/prometheus.yml
  name: prometheus-yml
  options:
    disableNameSuffixHash: true
- files:
  - rabbitmq.conf=etc/rabbitmq.conf
  - enabled_plugins=etc/enabled_plugins
  name: fnal-rabbitmq-conf

secretGenerator:
- files:
  - __init__.py=etc/policy-package/__init__.py
  - permission.py=etc/policy-package/permission.py
  - schema.py=etc/policy-package/schema.py
  - lfn2pfn.py=etc/policy-package/lfn2pfn.py
  - path_gen.py=etc/policy-package/path_gen.py
  - utils.py=etc/policy-package/utils.py
  name: fnal-policy-package
- files:
  - docker-entrypoint.sh=etc/docker-entrypoint-server.sh
  name: fnal-docker-entrypoint-server
- files:
  - start-daemon.sh=etc/docker-entrypoint-daemons.sh
  name: fnal-docker-entrypoint-daemons
- files:
  - automatix.json=etc/automatix.json
  name: fnal-automatix-json
  options:
    disableNameSuffixHash: true
- files:
  - vomses=etc/vomses
  name: fnal-vomses
- files:
  - fnal-custom-config.conf=etc/fnal-custom-config.conf
  name: fnal-httpd-custom-config
