# kustomize.yaml for rucio-dune-dev
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- helm-rucio-server.yaml
- helm-rucio-daemons.yaml
- helm-rucio-webui.yaml
- cache.yaml
- prometheus.yaml
- messenger.yaml
- grid-certificates-pvc.yaml
- grid-certificates-cronjob.yaml
- grid-certificates-job.yaml

patches:
- path: patch-service.yaml
- path: grid-certificates-patch.yaml
- path: patch-webui.yaml
- path: patch-busybox.yaml
- path: patch-renew-fts-proxy-job.yaml

configMapGenerator:
- files:
  - next.config.js=etc/next.config.js
  name: webui-patch
- files:
  - rucio.conf.j2=etc/rucio.conf.j2
  name: webui-rucio-conf-j2

secretGenerator:
- files:
  - __init__.py=etc/policy-package/__init__.py
  - permission.py=etc/policy-package/permission.py
  - schema.py=etc/policy-package/schema.py
  - lfn2pfn.py=etc/policy-package/lfn2pfn.py
  - path_gen.py=etc/policy-package/path_gen.py
  name: fnal-policy-package
- literals:
  - hostcert.pem=
  - hostkey.pem=
  name: fnal-rucio-x509up
  options:
    disableNameSuffixHash: true
- files:
  - automatix.json=etc/automatix.json
  name: fnal-automatix-json
  options:
    disableNameSuffixHash: true
- files:
  - vomses=etc/vomses
  name: fnal-vomses
- files:
  - rabbitmq.conf=etc/rabbitmq.conf
  name: fnal-rabbitmq-conf
- files:
  - enabled_plugins=etc/enabled_plugins
  name: fnal-rabbitmq-enabled-plugins
- files:
  - fnal-custom-config.conf=etc/fnal-custom-config.conf
  name: fnal-httpd-custom-config
