---
# Source: rucio-server/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: fnal-rucio-server.config.common
  labels:
    app: rucio-server
    chart: "rucio-server"
    release: "fnal"
    heritage: "Helm"
type: Opaque
data:
  common.json: "ewogICJvaWRjIjogewogICAgImFkbWluX2lzc3VlciI6ICJDSUxvZ29uIiwKICAgICJpZHBzZWNyZXRzIjogIi9vcHQvcnVjaW8vZXRjL2lkcHNlY3JldHMuanNvbiIsCiAgICAic3VwcG9ydHNfYXVkaWVuY2UiOiAiRmFsc2UiCiAgfSwKICAicG9saWN5IjogewogICAgInBhY2thZ2UiOiAiZmVybWlsYWIiCiAgfSwKICAid2VidWkiOiB7CiAgICAidXJscyI6ICJodHRwczovL3dlYnVpLWljYXJ1cy1ydWNpby5mbmFsLmdvdiIKICB9Cn0="
---
# Source: rucio-server/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: fnal-rucio-server.cfg
  labels:
    app: rucio-server
    chart: "rucio-server-35.0.1"
    release: "fnal"
    heritage: "Helm"
type: Opaque
data:
  grid_site_enabled: "VHJ1ZQ=="
---
# Source: rucio-server/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fnal-rucio-server
  labels:
    app: rucio-server
    chart: rucio-server-35.0.1
    release: fnal
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
  selector:
    app: rucio-server
    release: fnal
---
# Source: rucio-server/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fnal-rucio-server
  labels:
    app: rucio-server
    chart: rucio-server-35.0.1
    release: fnal
    heritage: Helm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rucio-server
      release: fnal
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: rucio-server
        release: fnal
      annotations:
        checksum/config: 436ba0991ad4d4cc07f0685a148c525e1191298c
    spec:
      serviceAccountName: useroot
      volumes:
      - name: config
        secret:
          secretName: fnal-rucio-server.config.common
      - name: httpdlog
        emptyDir: {}
      - name: policy-package
        secret:
          secretName: fnal-policy-package
      - name: httpd-custom-config
        secret:
          secretName: fnal-httpd-custom-config
      - name: ca-volume
        secret:
          secretName: fnal-ca-volume
      - name: server-hostcert
        secret:
          secretName: fnal-server-hostcert
      - name: server-hostkey
        secret:
          secretName: fnal-server-hostkey
      - name: idpsecrets
        secret:
          secretName: fnal-idpsecrets
      containers:
        - name: httpd-error-log
          image: busybox
          args: [/bin/sh, -c, 'tail -n+1 -F /var/log/httpd/error_log']
          volumeMounts:
          - name: httpdlog
            mountPath: /var/log/httpd
          resources:
            limits:
              cpu: 30m
              memory: 50Mi
            requests:
              cpu: 20m
              memory: 20Mi
        - name: rucio-server
          image: "imageregistry.fnal.gov/docker.io/rucio/rucio-server:release-37.2.0"
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1000m
              memory: 2000Mi
            requests:
              cpu: 700m
              memory: 2000Mi
          volumeMounts:
          - name: config
            mountPath: /opt/rucio/etc/conf.d/10_common.json
            subPath: common.json
          - name: httpdlog
            mountPath: /var/log/httpd
          - name: policy-package
            mountPath: /opt/rucio/permissions/fermilab
            subPath: 
          - name: httpd-custom-config
            mountPath: /etc/httpd/conf.d/fnal-custom-config.conf
            subPath: fnal-custom-config.conf
          - name: ca-volume
            mountPath: /etc/grid-security/certificates
            subPath: 
          - name: server-hostcert
            mountPath: /etc/grid-security/hostcert.pem
            subPath: hostcert.pem
          - name: server-hostkey
            mountPath: /etc/grid-security/hostkey.pem
            subPath: hostkey.pem
          - name: idpsecrets
            mountPath: /opt/rucio/etc/idpsecrets.json
            subPath: idpsecrets.json
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
            - name: health
              containerPort: 444
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ping
              port: 444
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /ping
              port: 444
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
          env:
            - name: RUCIO_HTTPD_GRID_SITE_ENABLED
              valueFrom:
                secretKeyRef:
                  name: fnal-rucio-server.cfg
                  key: grid_site_enabled
            - name: RUCIO_ENABLE_SSL
              value: "True"
            - name: RUCIO_HEALTH_CHECK_PORT
              value: "444"
            - name: RUCIO_SERVER_TYPE
              value: "api"
            - name: RUCIO_OVERRIDE_CONFIGS
              value: "/opt/rucio/etc/conf.d/"
            - name: RUCIO_LOG_FORMAT
              value: '[%{%Y-%m-%d %H:%M:%S}t]\t%v\t%h\t%{X-Forwarded-For}i\t%{X-Rucio-RequestId}i\t%>s\t%I\t%B\t%D\t\"%r\"\t\"%{X-Rucio-Account}i\"\t\"%{User-Agent}i\"\t%{X-Rucio-Script}i'
            - name: RUCIO_WSGI_DAEMON_PROCESSES
              value: "4"
            - name: RUCIO_WSGI_DAEMON_THREADS
              value: "4"
            - name: PYTHONPATH
              value: /opt/rucio/permissions
            - name: RUCIO_CFG_DATABASE_DEFAULT
              valueFrom:
                secretKeyRef:
                  key: db-connstr.txt
                  name: fnal-db-connstr
            - name: RUCIO_HTTPD_LEGACY_DN
              value: "True"
            - name: RUCIO_CA_PATH
              value: /etc/grid-security/certificates
      affinity:
