
resources:
- helm-rucio-server.yaml
- helm-rucio-daemons.yaml
- helm-rucio-webui.yaml
- cache.yaml
- prometheus.yaml
- messenger.yaml
- grid-certificates-pvc.yaml
- grid-certificates-cronjob.yaml
- grid-certificates-job.yaml

patchesStrategicMerge:
- patch-service.yaml
- grid-certificates-patch.yaml
- patch-busybox.yaml
- patch-renew-fts-proxy-job.yaml
#- rucio-env-patch.yaml

secretGenerator:
# The desired policy package implementation files
- name: fnal-policy-package
  files:
  - __init__.py=etc/policy-package/__init__.py
  - permission.py=etc/policy-package/permission.py
  - schema.py=etc/policy-package/schema.py

# Used by daemons
- name: fnal-rucio-x509up
  literals:
  - hostcert.pem=
  - hostkey.pem=
  options:
    disableNameSuffixHash: true
- name: fnal-automatix-json
  files:
  - automatix.json=etc/automatix.json
  options:
    disableNameSuffixHash: true

# VOMS Server File (used for getting VOMS proxies in the ftsRenewal Job)
- name: fnal-vomses
  files:
  - vomses=etc/vomses

# RabbitMQ Configuration Files
- name: fnal-rabbitmq-conf
  files:
  - rabbitmq.conf=etc/rabbitmq.conf
- name: fnal-rabbitmq-enabled-plugins
  files:
  - enabled_plugins=etc/enabled_plugins

# Custom HTTPD config options for Fermilab
- name: fnal-httpd-custom-config
  files:
  - fnal-custom-config.conf=etc/fnal-custom-config.conf
