apiVersion: v1
kind: Pod
metadata:
  name: psql-client
spec:
  containers:
    - name: psql
      image: postgres:latest
      command: ["sleep", "infinity"]
      resources:
        requests:
          cpu: 250m
          memory: 384Mi
        limits:
          cpu: "1"
          memory: 1Gi
      env:
        - name: RUCIO_CFG_DATABASE_DEFAULT
          valueFrom:
            secretKeyRef:
              name: fnal-db-connstr
              key: db-connstr.txt
