global:
  scrape_interval: 60s
  evaluation_interval: 60s

remote_write:
  - url: "http://lsdataitb.fnal.gov:9009/api/v1/push"
    write_relabel_configs:
      - target_label: "rucio_deployment"
        replacement: rucio-dune

scrape_configs:

  - job_name: rucio-daemons
    honor_labels: true

    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - "rucio-dune"
        selectors:
        - role: "pod"
          label: "app-group=rucio-daemons"

    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_name]
        action: drop
        regex: .+abacus.+
      #- action: labelmap
      #  regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__address__]
        action: replace
        regex: ([^:]+):.*
        replacement: $1:8080
        target_label: __address__

  - job_name: rucio-pgb-tx
    honor_labels: true

    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - "rucio-dune"
        selectors:
        - role: "pod"
          label: "app=rucio-pgb-cnpg-tx"

    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_container_name]
        action: keep
        regex: pgbouncer-exporter
      #- action: labelmap
      #  regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__address__]
        action: replace
        regex: ([^:]+):.*
        replacement: $1:9127
        target_label: __address__

  - job_name: rucio-messenger-rabbitmq
    honor_labels: true

    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - "rucio-dune"
        selectors:
        - role: "pod"
          label: "app=rucio-messenger"

    relabel_configs:
      # Scrape only pods that have the app label set to 'rabbitmq'
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: rucio-messenger
      # Direct Prometheus to the dedicated metrics port (15692)
      - source_labels: [__address__]
        action: replace
        regex: ([^:]+)(?::\d+)?
        replacement: $1:15692
        target_label: __address__
