apiVersion: apps/v1
kind: Deployment
metadata:
  name: fnal-rucio-webui
spec:
  template:
    spec:
      containers:
        - name: httpd-error-log
          resources:
            limits:
              cpu: 30m
              memory: 50Mi
            requests:
              cpu: 20m
              memory: 20Mi
        - name: webui-log
          resources:
            limits:
              cpu: 30m
              memory: 50Mi
            requests:
              cpu: 20m
              memory: 20Mi
