definitions.import_backend = local_filesystem
definitions.local.path = /etc/rabbitmq/definitions.json

log.console.level = debug
loopback_users.guest = true
ssl_options.cacertfile = /etc/grid-security/rabbitmq/ca.pem
ssl_options.certfile = /etc/grid-security/rabbitmq/hostcert.pem
ssl_options.fail_if_no_peer_cert = true
ssl_options.keyfile = /etc/grid-security/rabbitmq/hostkey.pem
ssl_options.verify = verify_peer
ssl_options.depth  = 5


ssl_options.versions.1 = tlsv1.2

# ciphers from https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/TLS_Cipher_String_Cheat_Sheet.md advanced list. Some of these are actually TLS1.3 ciphers and so won't work, but this should be compatible with openssl 1.0.1e+, and so SL6+

#ssl_options.ciphers.1 = TLS_AES_256_GCM_SHA384
#ssl_options.ciphers.2 = TLS_CHACHA20_POLY1305_SHA256
#ssl_options.ciphers.3 = TLS_AES_128_GCM_SHA256
ssl_options.ciphers.1 = DHE-RSA-AES256-GCM-SHA384
ssl_options.ciphers.2 = DHE-RSA-AES128-GCM-SHA256
ssl_options.ciphers.3 = ECDHE-RSA-AES256-GCM-SHA384
ssl_options.ciphers.4 = ECDHE-RSA-AES128-GCM-SHA256

#ssl_options.honor_cipher_order = true
#ssl_options.honor_ecc_order    = true

hipe_compile = false

listeners.tcp = none
stomp.listeners.tcp.1 = 0.0.0.0:61613
stomp.listeners.ssl.1 = 0.0.0.0:443

# Management
management.tcp.port = 15672
management.ssl.port = 15671
management.ssl.cacertfile = /etc/grid-security/rabbitmq/ca.pem
management.ssl.certfile = /etc/grid-security/rabbitmq/hostcert.pem
management.ssl.keyfile = /etc/grid-security/rabbitmq/hostkey.pem
management.ssl.verify = verify_peer
management.ssl.fail_if_no_peer_cert = true
